services:
  apollo:
    container_name: apollo
    image: apollo
    ports:
      - "6969:6969"
    volumes:
      - path/to/your/media/root:/media
      - path/to/where/you/want/apollo/data/stored:/data
    environment:
      - TMDB_API_KEY=yourApiKeyHere
      - TMDB_READ_ACCESS_TOKEN=yourReadAccessTokenHere