export { default as Dashboard } from './Dashboard'
export { default as Library } from './Library'
export { default as Configure } from './Configure'
export { default as FourOhFour } from './FourOhFour'
export { default as Series } from './Series'
export { default as Movie } from './Movie'
export { default as Login } from './Login'